In [5]:
import numpy as np
import time
n = 5000*5000
item = list(range(n))
start = time.time()
square = [x**2 for x in item ]
tt = time.time()- start

array = np.array(n)
start = time.time()
sq = array*array
ttt = time.time()- start

print(f"List time : {tt:.4f}")
print(f"Array time : {ttt:.4f}")


List time : 2.6257
Array time : 0.0001


In [8]:

import numpy as np
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [x+y for x,y in zip(l1,l2)]
print(l3)
arr1 = np.array(l1)
arr2 = np.array(l2)
arr3 = arr1 + arr2
print(arr3)

[5, 7, 9]
[5 7 9]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([[7,8,9],[4,5,6]])
print(arr1)
print()
print(arr2)






[1 2 3]

[[7 8 9]
 [4 5 6]]


In [3]:
import numpy as np
np.arange(1,6,2)

array([1, 3, 5])

In [1]:
import numpy as np
for i in range (2,20,2):
    print(np.arange(2,i+2,2))

[2]
[2 4]
[2 4 6]
[2 4 6 8]
[ 2  4  6  8 10]
[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12 14]
[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16 18]


In [7]:
myarr = np.array([[1,2,2],[2,5,9]])
print(myarr.shape)
print(myarr.size)
print(myarr.ndim)

(2, 3)
6
2


In [9]:
myarr.reshape(3,2)

array([[1, 2],
       [2, 2],
       [5, 9]])

In [2]:
# Slicing of array
arr4 = [1,2,3,4,5]
print(arr4[1:3])

[2, 3]


In [4]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arrr = np.array([1.1,2.2,3.3])
int_arr = arrr.astype(bool)
print(int_arr)

[ True  True  True]


In [28]:
ss = np.array([1,1,1,2,2,2,3,3,3])
ss.reshape(3,3)


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [37]:
sum([1*3,5])

8

In [ ]:
ss = np.array([1,1,1,2,2,2,3,3,3])
ss.reshape(3,3)


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [1]:
import numpy as np

In [5]:
arr5 = np.array([1,2,3])

print(arr5+5)

[6 7 8]


In [4]:
# Broadcasting example using normalization
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
u = x.mean(axis = 0)
s = x.std(axis = 0)
normal = (x-u)/s
print(normal)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [11]:
# Broadcasting example using normalization
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
u = x.mean()
s = x.std()
normal = (x-u)/s
print("Mean = ",  u, "Std = ",  s)
print(normal)
print(normal.mean())

Mean =  5.0 Std =  2.581988897471611
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0


In [19]:
#Mathematical Fuctions
a = np.array([1,2,3,4,5])
print(a.sum())

15


In [26]:
list = ([1,2,3,4,5,7])
i = np.array(list)
i

array([1, 2, 3, 4, 5, 7])

In [42]:
for i in range(2,21,2):
    t = np.arange(2,i+2,2)
print(t)

[ 2  4  6  8 10 12 14 16 18 20]
